### ISSUE TITLE
Travis failing due to activesupport gem

### ISSUE THREAD

**Issue by thejandroman** [gjtorikian/extended-markdown-filter#17]
activesupport >= 5.0 only support ruby >= 2.2.2

This is causing travis builds to fail. Consider locking the activesupport gem to ~> 4.2 or bumping the minimum supported ruby version to 2.2.2.

**Comment by thejandroman** [comment]
The activesupport gem is being brought in by the html-pipeline gem.

**Comment by gjtorikian** [comment]
Closed by #18
