### ISSUE TITLE
Example of Admonition in README

### ISSUE THREAD

**Issue by ketozhang** [gjtorikian/extended-markdown-filter#20]
Please add some graphical examples (screenshots will do) in README. Usually I like to see if a repo is worth installing if I see outputs.

**Comment by gjtorikian** [comment]
There's not much to screenshot, the result of an admonition is just some HTML. 

You can see an example of what styling it might look like here, https://help.github.com/articles/searching-for-repositories/#search-by-topic, since GitHub Help uses this gem.
