### ISSUE TITLE
Helper for admonitions

### ISSUE THREAD

**Issue by bernars** [gjtorikian/extended-markdown-filter#7]
Motivated by https://github.com/github/manual-of-style/issues/48, it would be rad to automatically display and format preface text for our four types of admonitions:
##### `{{note}}` (doesn't currently exist)

**Note:** Something the user may or may not need to know, but that isn't catastrophic or potentially catastrophic.
##### `{{tip}}`

**Tip:** Something the user might like to know that makes their life easier. This comes up in the UI a lot as "ProTip".
##### `{{warning}}`

**Warning:** Information the user should know to avoid _potential_ catastrophe or a loss of data.
##### `{{error}}`

**Danger:** Actions that _will_ cause catastrophe or a loss of data.

cc @github/docs

**Comment by gjtorikian** [comment]
Closed by https://github.com/gjtorikian/extended-markdown-filter/pull/11
